name: v_chat
description: "A new Flutter project."
publish_to: 'none'
version: 2.4.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore_web: ^4.0.3
  google_sign_in: ^6.2.1
  firebase_messaging_web: ^3.8.11
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.1+2
  workmanager: ^0.5.2
  image_picker: ^1.1.2
  path_provider: ^2.0.5
  video_player: ^2.2.11
  cached_network_image: ^3.1.0
  record: ^5.1.2
  cupertino_icons: ^1.0.6
  image_cropper: ^8.0.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.3.0
  cloud_functions: ^5.0.4
  http: ^1.2.2
  webview_flutter: ^4.8.0
  spotify_sdk: ^2.3.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_background.png
    - assets/images/empty_chat.png
    - assets/images/google_logo.png
    - assets/images/microsoft.png
    - assets/images/app_logo.png
    - assets/images/app_logo_transparent.png
    - assets/backgrounds/dark_mode_4.jpg
    - assets/backgrounds/dark_mode_1.jpg
    - assets/backgrounds/light_mode_1.jpg
    - assets/backgrounds/dark_mode_2.jpg
    - assets/backgrounds/light_mode_2.jpg
    - assets/backgrounds/dark_mode_3.jpg
    - assets/icons/effect_icon.png
    - assets/icons/send_icon.png
    - assets/icons/refresh.png
    - assets/icons/attach_icon.png
    - assets/icons/down.png
    - assets/icons/menu.png
    - assets/icons/profile.png
    - assets/icons/bell.png
    - assets/icons/lock.png
    - assets/icons/palette.png
    - assets/icons/logout.png
    - assets/icons/plus.png
    - assets/icons/settings.png
    - assets/icons/gif.png
    - assets/icons/gallery.png
    - assets/icons/camera.png
    - assets/icons/message.png
    - assets/icons/trash.png
    - assets/icons/edit.png
    - assets/icons/comment.png
    - assets/icons/heart.png
    - assets/icons/music.png
    - assets/icons/person.png